# netlify.toml

# This section configures the build command and publish directory.
# It should match what you have set in the Netlify UI.
[build]
  command = "npm run build"
  publish = ".next"

# This section configures Netlify's secrets scanning feature.
[build.processing.secrets]
  # Add the exact names of the environment variables that are 
  # INTENTIONALLY public and should be ignored by the scanner.
  omit_keys = [
    "NEXT_PUBLIC_FIREBASE_API_KEY",
    "NEXT_PUBLIC_FIREBASE_APP_ID",
    "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
    "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
    "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
    "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
  ]

  # In some workflows, example files or exported workflow files may contain placeholders
  # or public URLs that look like secrets. Omit those paths from scanning to avoid
  # false positives. Adjust as needed.
  # Paths to omit from secrets scanning. Include example files, build caches,
  # and Netlify's generated build output so the scanner doesn't flag generated
  # artifacts containing long hashes or inlined public env values.
  omit_paths = [
    "Workflow 2.json",
    ".env.example",
    "tsconfig.tsbuildinfo",
    ".next/cache/**",
    ".next/**/cache/**",
    ".netlify/.next/**",
    ".netlify/.next/cache/**",
    ".netlify/.next/cache/webpack/**"
  ]
