# netlify.toml

# This section configures the build command and publish directory.
# It should match what you have set in the Netlify UI.
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_ENABLED = "limited"
  # Configure secrets scan to skip public env vars
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_FIREBASE_API_KEY,NEXT_PUBLIC_FIREBASE_APP_ID,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,NEXT_PUBLIC_FIREBASE_PROJECT_ID,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"

[build.processing.secrets]
  # Paths to omit from secrets scanning. Include example files, build caches,
  # and Netlify's generated build output to avoid flagging artifacts.
  omit_paths = [
    # Example and exported artifacts that may legitimately contain long hashes
    "Workflow 2.json",
    ".env.example",
    "tsconfig.tsbuildinfo",

    # Next build output and caches (match all generated files)
    ".next/**",
    ".next/cache/**",
    ".next/*/cache/**",
    ".next/static/**",
    ".next/server/**",

    # Netlify-specific build output (when Netlify packages .next into functions)
    ".netlify/.next/**",
    ".netlify/functions-internal/**",
    ".netlify/functions/**",

    # Cover common webpack pack/cache files
    ".next/cache/webpack/**",
    ".netlify/.next/cache/webpack/**"
  ]
