# netlify.toml

# This section configures the build command and publish directory.
# It should match what you have set in the Netlify UI.
[build]
  command = "npm run build"
  publish = ".next"

# This section configures Netlify's secrets scanning feature.
[build.processing.secrets]
  # Add the exact names of the environment variables that are 
  # INTENTIONALLY public and should be ignored by the scanner.
  omit_keys = [
    "NEXT_PUBLIC_FIREBASE_API_KEY",
    "NEXT_PUBLIC_FIREBASE_APP_ID",
    "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
    "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
    "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
    "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
  ]

  # Omit the actual public Firebase config values from secrets scanning in generated output
  omit_values = [
    "AIzaSyCo8uQVz6R-EybkSh6c_7q4jmtFysrNE2U", # NEXT_PUBLIC_FIREBASE_API_KEY
    "andreasb-7371d.firebaseapp.com", # NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
    "andreasb-7371d", # NEXT_PUBLIC_FIREBASE_PROJECT_ID
    "andreasb-7371d.firebasestorage.app", # NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
    "557451963317", # NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
    "1:557451963317:web:f010e64c9a13f1848e47fc" # NEXT_PUBLIC_FIREBASE_APP_ID
  ]

  # In some workflows, example files or exported workflow files may contain placeholders
  # or public URLs that look like secrets. Omit those paths from scanning to avoid
  # false positives. Adjust as needed.
  # Paths to omit from secrets scanning. Include example files, build caches,
  # and Netlify's generated build output so the scanner doesn't flag generated
  # artifacts containing long hashes or inlined public env values.
  omit_paths = [
    # Example and exported artifacts that may legitimately contain long hashes
    "Workflow 2.json",
    ".env.example",
    "tsconfig.tsbuildinfo",

    # Next build output and caches (match all generated files)
    ".next/**",
    ".next/cache/**",
    ".next/*/cache/**",
    ".next/static/**",
    ".next/server/**",

    # Netlify-specific build output (when Netlify packages .next into functions)
    ".netlify/.next/**",
    ".netlify/functions-internal/**",
    ".netlify/functions/**",

    # Cover common webpack pack/cache files
    ".next/cache/webpack/**",
    ".netlify/.next/cache/webpack/**"
  ]
